networks:
  frontend:
    driver: bridge
  backend: 
    driver: bridge

services:
  backend:
    image: php:fpm
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: foliode_backend
    working_dir: /var/www/html
    command: php -S 0.0.0.0:9000 -t public
    volumes:
      - ./backend:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      SYMFONY_ENV: ${SYMFONY_ENV:-dev}
      DATABASE_URL: "${POSTGRES_URL}"
      MAILER_DSN: "${MAILER_DSN}"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: foliode_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    env_file:
      - .env
    networks:
      - frontend
  db:
    image: postgres:13
    container_name: symfony_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - ${DB_PORT}:5432
  web:
    image: nginx:alpine
    container_name: nginx_web
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./backend/public:/var/www/html/public
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - frontend
      - backend
volumes:
  db_data: