FROM php:8.2-fpm

RUN apt-get update && apt-get install -y \
    libpq-dev \
    git \
    unzip \
    && docker-php-ext-install pdo pdo_pgsql

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

COPY . .

RUN composer install --prefer-dist --no-dev --no-scripts --no-progress --no-interaction

COPY php-mail.ini /usr/local/etc/php/conf.d/php-mail.ini

EXPOSE 9000

CMD ["php-fpm"]
